### PR TITLE
Added support for custom folder links (and shorthands for audio-related system folders)

### PR DESCRIPTION
**Pull request by zetenynagy**
Added support for folder links for VST, VST3, Audio Unit (Component), CLAP and HAL (driver) system folders. 

This is useful and handy as sometimes for users to install 'homebrew' audio plug-ins it is frustrating to navigate to these system folders manually.

### CODE REVIEW

**Comment by zetenynagy** [comment]
Added support for custom folder links with customizable display names

**Comment by aonez** [comment]
@zetenynagy sorry I did not reply because I'm not well versed on audio components. Was hoping someone else could help reviewing here.

What I liked is the idea of the custom drop link. This can be improved to accept more than one (like `add-file`) and then it can be used to all those audio ones. What do you think?

**Comment by zetenynagy** [comment]
@aonez Could the users just use multiple instances of `--custom-path-link` instead of it taking multiple items? For legibility reasons - having all of those parameters along with positioning etc. might get cluttered. It's not hard, so if you think it's better, I could change it anyway.

The audio folder links are very useful and not as _niche_ as they sound. I have encountered many open source audio plug-ins that would have benefited from having these links. If you don't want to merge these changes however, I can make a separate branch with just the custom folder links.

**Comment by mhhollomon** [comment]
I would love to see this merged as I have this exact use-case (VST3 plugins). 
I would say that the custom-links is probably all that is needed.

**Comment by aonez** [comment]
@zetenynagy If you could do that, change `custom-path-link` to `add-drop-link` and be able to accept multiple instances, that would be awesome. Also move that one to README's line 62, so it goes before the `ql-drop-link` and all the audio shorthands.

That way there'll be the _shorthands_ for audio and custom drop links for everything else. Thanks again for this contribution 🙌🏼

**Comment by mhhollomon** [comment]
Used this in a workflow and found out that the audio library paths are not necessarily there in the github runner macOS images. (e.g. /Library/Audio/Plug-Ins/VST3 did not exist).

So, the check that it exists needs to be taken out (the code doesn't check for the shortcuts).
Or another option --skip-drop-link-check could be added.

**Comment by zetenynagy** [comment]
@aonez Sure thing - I'll try to do that soon-ish.

@mhhollomon If I recall correctly, apparently the VST3 folder is not there by default, and the installers of some VST3 plug-ins actually create the launchers. I might be wrong on this though.
I understand why taking out the check makes sense though - creating aliases for folders that do not currently exist on the machine, but are expected to be there on the end user's machine?

**Comment by zetenynagy** [comment]
@mhhollomon - I have added the functionality that you requested, you can now skip the verification, and as an alternative if the verification is not skipped and fails, the script can try to create the nonexistent folder before adding the link.
I have renamed my branch, and have accidentally closed the pull request in the process - you can try the new version at pull request #162

**Pull request closed without merging**
